### ISSUE TITLE
projects page shows source

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/onedotcf#5]

**Comment by thecoder876** [comment]
@wgyt wdym

**Comment by wgyt** [comment]
> @wgyt wdym

it should link to /projects not /projects.md

**Comment by thecoder876** [comment]
> > [ping removed] wdym
> 
> it should link to /projects not /projects.md

@wgyt if it links to that it doesn't work

**Comment by wgyt** [comment]
fixed in https://github.com/onedotprojects/onedotcf/commit/8704c2525f4e9ac628b432f207e4e1cc702c2e53
